### ISSUE TITLE
What are the available RPC addresses for StateSync?

### ISSUE THREAD

**Issue by YuXiaoCoder** [bandprotocol/chain#275]

**Comment by RogerKSI** [comment]
Hi, 

## For Mainnet
- http://rpc.laozi1.bandchain.org:80
- http://rpc.laozi2.bandchain.org:80
- https://rpc.laozi3.bandchain.org:443
- https://rpc.laozi4.bandchain.org:443

In case, you can't find an upgraded snapshot for StateSync, you can add our peers [(list)](https://github.com/bandprotocol/launch/tree/master/laozi-mainnet) to be your persistent_peers.

Note: state sync on Mainnet requires at least 32 GB of RAM.

## For Testnet
- https://rpc.laozi-testnet6.bandchain.org:443

You can follow the steps in this [doc](https://github.com/bandprotocol/launch/blob/master/band-laozi-testnet6/docs/how-to-join-as-a-validator-using-statesync.md)

**Comment by YuXiaoCoder** [comment]
My configuration related to StateSync is as follows:
```toml
seeds = "8d42bdcb6cced03e0b67fa3957e4e9c8fd89015a@34.87.86.195:26656,543e0cab9c3016a0e99775443a17bcf163038912@34.150.156.78:26656,2c884e60a0944958a2a9389f07f2f66dcfc3add0@seeds-bandprotocol.activenodes.io:36656"

persistent_peers = "98823087b61d442a4ab86998709c77b2e517ee78@35.240.152.216:26656,3ea84babead3d6bc488810a0f2cf0744cf5c68fe@34.86.22.251:26656,d047cfabdfd5e244af530d6d2101d07c45ff7424@165.22.167.234:41656,1a4af7cbd3db94a3881dc35cfa261ec2ac788f8f@91.246.64.247:26656,c1b93580023f12891683431e25fb05d6e4372bef@188.34.207.243:26656,2f62588be3cf41a019289097c2068c4e65aa5e37@95.217.213.135:26656,58ce8a2bd441057c0b18d0812f692b2d8af55af7@168.119.61.205:26656,570787c6484fb5aef9182f032dbd54042d93b93c@35.82.85.220:26656,cb777d12ec515884f9f8153e2bbe1844079323a4@44.234.200.116:26656,cacb630ef586ffefccf103d442c02bdbc187f996@3.37.82.201:26656,39d45dae55f36db42ef3997376efbbf725666f75@51.38.53.4:30656,70c542ec2e1aebb385f7e93d1c55f1a4073cdcb7@54.38.46.124:30656,d7e04f00e2701cb9b2c62a78b2e7bb3cdb165dfb@51.91.67.48:30656"

# StateSync
[statesync]
enable = true
rpc_servers = "https://rpc.laozi3.bandchain.org:443,https://rpc.laozi4.bandchain.org:443"
trust_height = 11538742
trust_hash = "1C873CA4A7E66B818D52293FABDAB3ADCDF12CBCA51DB7B14BF3B05596588469"
trust_period = "336h0m0s"
```

As a result, you still cannot connect to Peer. The log is as follows
```log
10:25AM INF Reconnecting to peer addr={"id":"d7e04f00e2701cb9b2c62a78b2e7bb3cdb165dfb","ip":"51.91.67.48","port":30656} module=p2p
10:25AM INF Dialing peer address={"id":"d7e04f00e2701cb9b2c62a78b2e7bb3cdb165dfb","ip":"51.91.67.48","port":30656} module=p2p
10:25AM INF service start impl="Peer{MConn{44.234.200.116:26656} cb777d12ec515884f9f8153e2bbe1844079323a4 out}" module=p2p msg={} peer={"id":"cb777d12ec515884f9f8153e2bbe1844079323a4","ip":"44.234.200.116","port":26656}
10:25AM INF service start impl=MConn{44.234.200.116:26656} module=p2p msg={} peer={"id":"cb777d12ec515884f9f8153e2bbe1844079323a4","ip":"44.234.200.116","port":26656}
10:25AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
10:25AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"cb777d12ec515884f9f8153e2bbe1844079323a4","ip":"44.234.200.116","port":26656}
10:25AM INF service stop impl={"Logger":{}} module=p2p msg={} peer={"id":"cb777d12ec515884f9f8153e2bbe1844079323a4","ip":"44.234.200.116","port":26656}
10:25AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
10:25AM INF service stop impl={"Data":{},"Logger":{}} module=p2p msg={} peer={"id":"cb777d12ec515884f9f8153e2bbe1844079323a4","ip":"44.234.200.116","port":26656}
10:25AM INF Reconnecting to peer addr={"id":"cb777d12ec515884f9f8153e2bbe1844079323a4","ip":"44.234.200.116","port":26656} module=p2p
10:25AM INF Dialing peer address={"id":"cb777d12ec515884f9f8153e2bbe1844079323a4","ip":"44.234.200.116","port":26656} module=p2p
10:25AM INF service start impl="Peer{MConn{51.91.67.48:30656} d7e04f00e2701cb9b2c62a78b2e7bb3cdb165dfb out}" module=p2p msg={} peer={"id":"d7e04f00e2701cb9b2c62a78b2e7bb3cdb165dfb","ip":"51.91.67.48","port":30656}
10:25AM INF service start impl=MConn{51.91.67.48:30656} module=p2p msg={} peer={"id":"d7e04f00e2701cb9b2c62a78b2e7bb3cdb165dfb","ip":"51.91.67.48","port":30656}
10:25AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
10:25AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"d7e04f00e2701cb9b2c62a78b2e7bb3cdb165dfb","ip":"51.91.67.48","port":30656}
10:25AM INF service stop impl={"Logger":{}} module=p2p msg={} peer={"id":"d7e04f00e2701cb9b2c62a78b2e7bb3cdb165dfb","ip":"51.91.67.48","port":30656}
10:25AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
10:25AM INF service stop impl={"Data":{},"Logger":{}} module=p2p msg={} peer={"id":"d7e04f00e2701cb9b2c62a78b2e7bb3cdb165dfb","ip":"51.91.67.48","port":30656}

10:26AM INF Reconnecting to peer addr={"id":"cb777d12ec515884f9f8153e2bbe1844079323a4","ip":"44.234.200.116","port":26656} module=p2p
10:26AM INF Dialing peer address={"id":"cb777d12ec515884f9f8153e2bbe1844079323a4","ip":"44.234.200.116","port":26656} module=p2p
10:26AM INF Saving AddrBook to file book=/mnt/bandmain/node/config/addrbook.json module=p2p size=367
10:26AM INF Ensure peers module=pex numDialing=3 numInPeers=0 numOutPeers=3 numToDial=4
10:26AM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
10:26AM INF Dialing peer address={"id":"ebc272824924ea1a27ea3183dd0b9ba713494f83","ip":"185.16.39.158","port":26666} module=p2p
10:26AM INF Dialing peer address={"id":"c721a74492d3f863c1e1f33b5932d7a54cfb5776","ip":"34.150.156.78","port":26656} module=p2p
10:26AM INF Dialing peer address={"id":"2c2b504d20b7d5208e69863344e5112ac2972ca6","ip":"15.188.8.207","port":26656} module=p2p
10:26AM INF Dialing peer address={"id":"b91f49859a881346878cdb39566b87a75a127a38","ip":"46.101.102.198","port":52656} module=p2p
```
